// <auto-generated />
using EntityFrameworkWinForms.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkWinForms.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20250616151706_UpdateToStudents")]
    partial class UpdateToStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFrameworkWinForms.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CuratorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CuratorId");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("EntityFrameworkWinForms.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Avg")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("groupeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("groupeId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("EntityFrameworkWinForms.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("EntityFrameworkWinForms.Models.Group", b =>
                {
                    b.HasOne("EntityFrameworkWinForms.Models.Teacher", "Curator")
                        .WithMany()
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curator");
                });

            modelBuilder.Entity("EntityFrameworkWinForms.Models.Student", b =>
                {
                    b.HasOne("EntityFrameworkWinForms.Models.Group", "groupe")
                        .WithMany()
                        .HasForeignKey("groupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("groupe");
                });
#pragma warning restore 612, 618
        }
    }
}
